App\Modules\User\Domain\AuthToken:
  attributes:
    id:
      groups:
        [ 'auth-token', 'user' ]
    token:
      groups:
        [ 'auth-token' ]
    name:
      groups:
        [ 'auth-token', 'user' ]
    user:
      groups:
        [ 'auth-token' ]
    createdAt:
      groups:
        [ 'auth-token', 'user' ]
    lastUsedAt:
      groups:
        [ 'auth-token', 'user' ]
