App\Modules\User\Domain\User:
  attributes:
    id:
      groups: [ 'user', 'auth-token' ]
    email:
      groups: [ 'user', 'auth-token' ]
    firstName:
      groups: [ 'user', 'auth-token' ]
    lastName:
      groups: [ 'user', 'auth-token' ]
    roles:
      groups: [ 'user', 'auth-token' ]
    createdAt:
      groups: [ 'user' ]
    authTokens:
      groups: [ 'user' ]
    userIdentifier:
      ignore: true
