App\Modules\User\Domain\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: email
        message: "Email is already taken"
  properties:
    email:
      - Email: ~
